-- ============================================================
-- SiteStore — schemat bazy danych Supabase
-- Uruchom w: Supabase Dashboard → SQL Editor
-- ============================================================

-- Tabela katalogu stron
create table if not exists public.websites (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  title       text not null,
  url         text not null,
  description text,
  likes       integer not null default 0,
  is_approved boolean not null default false
);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.websites enable row level security;

-- 1) Publiczny odczyt WYŁĄCZNIE zatwierdzonych rekordów
create policy "Public can read approved websites"
  on public.websites
  for select
  to anon, authenticated
  using (is_approved = true);

-- 2) Publiczne zgłaszanie stron — tylko z is_approved = false
create policy "Public can submit unapproved websites"
  on public.websites
  for insert
  to anon, authenticated
  with check (is_approved = false and likes = 0);

-- (Brak polityki UPDATE/DELETE dla anon — polubienia idą przez RPC poniżej)

-- ============================================================
-- RPC: atomowy inkrement polubień
-- SECURITY DEFINER pozwala zwiększyć licznik bez otwierania
-- pełnych uprawnień UPDATE dla klientów anonimowych.
-- ============================================================
create or replace function public.increment_likes(website_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.websites
  set likes = likes + 1
  where id = website_id
    and is_approved = true;
$$;

grant execute on function public.increment_likes(bigint) to anon, authenticated;

-- ============================================================
-- Przykładowe dane startowe (zatwierdzone)
-- ============================================================
insert into public.websites (title, url, description, likes, is_approved) values
  ('Remove.bg',       'https://www.remove.bg',    'Automatyczne usuwanie tła ze zdjęć w kilka sekund dzięki AI. Wgraj obrazek, a algorytm zrobi resztę.', 128, true),
  ('Slow Roads',      'https://slowroads.io',     'Relaksująca, nieskończona jazda samochodem przez proceduralnie generowane krajobrazy. Prosto w przeglądarce.', 94, true),
  ('Excalidraw',      'https://excalidraw.com',   'Wirtualna tablica do szkicowania diagramów o ręcznie rysowanym charakterze. Idealna do szybkich schematów.', 211, true),
  ('Photopea',        'https://www.photopea.com', 'Darmowy edytor graficzny w przeglądarce — niemal pełen Photoshop bez instalacji. Obsługuje PSD, XCF i Sketch.', 187, true),
  ('Radio Garden',    'https://radio.garden',     'Obracaj globusem i słuchaj tysięcy stacji radiowych na żywo z całego świata. Podróżuj dźwiękiem.', 156, true),
  ('TinyWow',         'https://tinywow.com',      'Ogromny zestaw darmowych narzędzi do PDF, wideo, obrazków i tekstu. Wszystko w jednym miejscu, bez rejestracji.', 73, true);
